# Makefile for compiling, installing and packing Emmet MonoDevelop plugin on Mono
#
#   run 'make' to compile the plugin against the installed version of MonoDevelop detected by ./configure.sh
#   run 'make install' to compile and install the plugin against the installed version of MonoDevelop detected by ./configure.sh
#   run 'make pack-all' to create a deployment binary packages for the known set of supported MonoDevelop versions

VERSION=0.1.1

MDTOOL=INSERT_MAKE_MDTOOL

MDROOT=INSERT_MAKE_MDROOT

# (MDVERSION) can be set to something like (3.0.4) to compile
# against the dependencies/... binaries for a specific version of MonoDevelop. This allows
# us to prepare new editions of the binding for several different versions of MonoDevelop.
MDVERSION=INSERT_MAKE_MDVERSION

MDTAG=local

# The default configuration is Debug
ifeq ($(config),)
config=Debug
endif

all: pack

build: src/MonoDevelop.EmmetPlugin/MonoDevelop.EmmetPlugin.$(MDTAG).csproj src/MonoDevelop.EmmetPlugin/MonoDevelop.Emmet.$(MDTAG).addin.xml
	rm -fr bin/$(MDTAG)/$(config)
	mkdir -p bin/$(MDTAG)/$(config)
	(cd src/MonoDevelop.EmmetPlugin && xbuild MonoDevelop.EmmetPlugin.$(MDTAG).csproj /p:Configuration=$(config))

pack: build
	# cp -pr bin/$(config)/* bin/$(MDTAG)/$(config)/
	-rm -fr pack/$(VERSION)/$(MDTAG)/$(config)
	@-mkdir -p pack/$(VERSION)/$(MDTAG)/$(config)
	$(MDTOOL) setup pack bin/$(MDTAG)/$(config)/MonoDevelop.Emmet.$(MDTAG).addin.xml -d:pack/$(VERSION)/$(MDTAG)/$(config)

clean:
	-rm -fr bin
	-rm -fr pack
	-rm -fr src/MonoDevelop.EmmetPlugin/MonoDevelop.Emmet.*.addin.xml
	-rm -fr src/MonoDevelop.EmmetPlugin/MonoDevelop.EmmetPlugin.*.csproj

src/MonoDevelop.EmmetPlugin/MonoDevelop.EmmetPlugin.$(MDTAG).csproj: src/MonoDevelop.EmmetPlugin/MonoDevelop.EmmetPlugin.csproj.orig
	sed \
		-e "s,INSERT_MDROOT,$(MDROOT),g" \
		-e "s,INSERT_CONFIG,$(config),g" \
		-e "s,INSERT_MDVERSION,$(MDVERSION),g" \
		-e "s,INSERT_MDTAG,$(MDTAG),g" \
		$< > $@

src/MonoDevelop.EmmetPlugin/MonoDevelop.Emmet.$(MDTAG).addin.xml: src/MonoDevelop.EmmetPlugin/MonoDevelop.Emmet.addin.xml.orig
	sed \
		-e "s,INSERT_VERSION,$(VERSION),g" \
		-e "s,INSERT_MDVERSION,$(MDVERSION),g" \
		-e "s,INSERT_MDTAG,$(MDTAG),g" \
		$< > $@

